/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "FreeRTOS.h"
#include "task.h"
#include "stm32f103x6.h"
#include "Stm32_F103C6_RCC_drivers.h"
#include "Stm32_F103C6_gpio_drivers.h"

TaskHandle_t vBlinkingLed = NULL;

void vBlinkingLed_Handler(void* parms);

void HW_init()
{
	GPIO_PinConfig_t PIN13C;
	PIN13C.GPIO_PinNumber = GPIO_PIN_13;
	PIN13C.GPIO_MODE = GPIO_MODE_OUTPT_PP;
	PIN13C.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;

	MCAL_GPIO_Init(GPIOC, &PIN13C);

}



int main(void)
{
    RCC_GPIOC_CLK_EN();
    HW_init();

    xTaskCreate(vBlinkingLed_Handler, "BlinkingLed", 128, NULL, 1, &vBlinkingLed);

    vTaskStartScheduler();

    while(1)
    {

    }

    return 0;
}


void vBlinkingLed_Handler(void* parms)
{
	while(1){
		MCAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, 0);
		vTaskDelay(100);
		MCAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, 1);
		vTaskDelay(100);


	}
}

