/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_EXTI_drivers.h"
#include "Stm32_F103C6_gpio_drivers.h"
#include "KEY_PAD.h"
#include "LCD.h"
#include "core_cm3.h"

uint32_t Task_A_Flag, Task_B_Flag, IRQ_Flag = 0;

#define TaskA_Stack_Size 100   //100 Bytes
#define TaskB_Stack_Size 100   //100 Bytes

extern int _estack;

// main stack
unsigned int _S_MSP = &_estack ;
unsigned int _E_MSP ;

// Process Stack Task A
unsigned int _S_PSP_TA ;
unsigned int _E_PSP_TA ;

// Process Stack Task B
unsigned int _S_PSP_TB ;
unsigned int _E_PSP_TB ;


#define OS_SET_PSP(add)						__asm volatile("mov R0 , %0 \n\t msr PSP, R0" :   :"r" (add))
#define OS_SWITCH_SP_TO_PSP					__asm volatile("MRS R0, CONTROL \n\t MOV R1,#0X02 \n\t ORR R0, R0,R1 \n\t MSR CONTROL, R0")
#define OS_SWITCH_SP_TO_MSP					__asm volatile("MRS R0, CONTROL \n\t MOV R1,#0X05 \n\t AND R0, R0,R1 \n\t MSR CONTROL, R0")

#define OS_Generate_Exeption				__asm volatile("SVC #0X03")


enum CPUaccesslevel{
	privileged,
	unprivileged
};




void SWITCH_CPU_AccessLevel(enum CPUaccesslevel level)
{
	switch (level) {
	case privileged:
		__asm("MRS R0 ,CONTROL \n\t"
				"LSR R0, #1 \n\t"
				"LSL R0, #1 \n\t"
				"MSR CONTROL, R0");
		break;
	case unprivileged:
		__asm("MRS R0 ,CONTROL \n\t"
				"ORR R0,#1\n\t"
				"MSR CONTROL, R0");
		break;
	default:
		break;
	}
}
void my_wait(int x)
{
	uint32_t i,j;
	for (i = 0; i < x; ++i)
		for (j = 0; j < 255; ++j);

}

void EXTI9_Callback (void)
{
	/*SWITCH_CPU_AccessLevel(privileged);
	LCD_clear_screen();
	IRQ_Flag =1;
	LCD_WRITE_STRING("IRQ EXTI9 is     happened _|- ");
	my_wait(1000);
	 */
	if (IRQ_Flag == 0)
	{
		Task_A_Flag =1;
		IRQ_Flag =1 ;
	}
	else if (IRQ_Flag == 1)
	{
		Task_B_Flag =1;
		IRQ_Flag =0 ;
	}
}

int Task_A ( int a, int b, int c)
{
	return a+b+c;
}


int Task_B( int a, int b, int c, int d)
{
	return a+b+c+d;
}

void Main_OS()
{
	//Main Stack
	_E_MSP= (_S_MSP - 512);

	// Task A
	_S_PSP_TA = (_E_MSP -8);
	_E_PSP_TA = (_S_PSP_TA - TaskA_Stack_Size);

	// Task B
	_S_PSP_TB = (_E_PSP_TA -8);
	_E_PSP_TB = (_S_PSP_TB - TaskB_Stack_Size);

	while(1){
		__asm("nop");
		if(Task_A_Flag == 1)
		{
			//set PSP Register = _S_PSP_TA
			OS_SET_PSP(_S_PSP_TA);
			//SP -> PSP
			OS_SWITCH_SP_TO_PSP;
			// Switch from privileged -> unprivileged
			SWITCH_CPU_AccessLevel(unprivileged);

			Task_A_Flag = Task_A(1, 2, 3);

			// Switch from unprivileged -> privileged
			OS_Generate_Exeption;
			//SP -> MSP
			OS_SWITCH_SP_TO_MSP;

		}
		else if (Task_B_Flag == 1)
		{
			//set PSP Register = _S_PSP_TB
			OS_SET_PSP(_S_PSP_TB);

			//SP -> PSP
			OS_SWITCH_SP_TO_PSP;
			// Switch from privileged -> unprivileged
			SWITCH_CPU_AccessLevel(unprivileged);

			Task_B_Flag = Task_B(1, 2, 3, 4);

			// Switch from unprivileged -> privileged
			OS_Generate_Exeption;

			//SP -> MSP
			OS_SWITCH_SP_TO_MSP;
		}
	}

}

void PendSV_Handler ()
{

}

void OS_SVC_Services(int * Stack_Frame_Pointer)
{
	//OS_SVC_Set Stack -> R0 -> argument 0 -> Stack_Frame_Pointer
	//OS_SVC_Set Stack : {R0,R1,R2,R3,R12,LR,PC,XPSR}
	unsigned char SVC_number;
	unsigned int val1,val2;
	SVC_number = *((unsigned char *)((unsigned char *)Stack_Frame_Pointer[6])-2);
	val1 = Stack_Frame_Pointer[0]; //R0 in OS_SVC_Set stack = First argument = a
	val1 = Stack_Frame_Pointer[1]; //R0 in OS_SVC_Set stack = Second argument = b

	switch(SVC_number)
		{
		case 1:	//ADD
			Stack_Frame_Pointer[0] =val1+val2;
			break;
		case 2:	//SUB
			Stack_Frame_Pointer[0] =val1-val2;
			break;
		case 3:	//MUL
			Stack_Frame_Pointer[0] =val1*val2;
			break;
		}
}

__attribute((naked)) void SVC_Handler ()	//Don't create a stack for this function
{

	__asm("TST LR, #0x04 \n\t"
			"ITE EQ \n\t"
			"MRSEQ R0, MSP \n\t"
			"MRSNE R0, PSP \n\t"
			"B OS_SVC_Services");
}

int OS_SVC_Set(int a, int b, int SVC_ID)
{
	int result;
	switch(SVC_ID)
	{
	case 1:	//ADD
		__asm("SVC #0x01");
		break;
	case 2:	//SUB
		__asm("SVC #0x02");
		break;
	case 3:	//MUL
		__asm("SVC #0x03");
		break;
	case 4:		//PendSV
		SCB->ICSR |= SCB_ICSR_PENDSVSET_Msk;
		break;

	}

	return result;
}
int main(void)
{
	//	/* Enable Clock */
	//	RCC_GPIOA_CLK_EN();
	//	RCC_GPIOB_CLK_EN();
	//	RCC_AFIO_CLK_EN();
	//
	//	LCD_INIT();
	//	LCD_clear_screen();
	//
	//	EXTI_GPIO_PinConfig_t EXTI_CFG;
	//	EXTI_CFG.EXTI_PIN = EXTIPB9;
	//	EXTI_CFG.Trigger_Case =EXTI_Trigger_Rising;
	//	EXTI_CFG.P_IRQ_CallBack = EXTI9_Callback;
	//	EXTI_CFG.IRQ_EN =EXTI_IRQ_Enable;
	//	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
	//	//
	//
	//	Main_OS();
	IRQ_Flag=1;
	IRQ_Flag = OS_SVC_Set(3, 3, 1);
	IRQ_Flag = OS_SVC_Set(3, 3, 2);
	IRQ_Flag = OS_SVC_Set(3, 3, 3);
	IRQ_Flag = OS_SVC_Set(3, 3, 4);

	while (1)
	{
		if(IRQ_Flag)
		{
			LCD_clear_screen();
			IRQ_Flag =0;

		}
	}
}
