/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_EXTI_drivers.h"
#include "Stm32_F103C6_gpio_drivers.h"
#include "KEY_PAD.h"
#include "LCD.h"

uint32_t Task_A_Flag, Task_B_Flag, IRQ_Flag = 0;


#define TaskA_Stack_Size 100   //100 Bytes
#define TaskB_Stack_Size 100   //100 Bytes

extern int _estack;

// main stack
unsigned int _S_MSP = &_estack ;
unsigned int _E_MSP ;

// Process Stack Task A
unsigned int _S_PSP_TA ;
unsigned int _E_PSP_TA ;

// Process Stack Task B
unsigned int _S_PSP_TB ;
unsigned int _E_PSP_TB ;


#define OS_SET_PSP(add)						__asm volatile("mov R0 , %0 \n\t msr PSP, R0" :   :"r" (add))
#define OS_SWITCH_SP_TO_PSP					__asm volatile("MRS R0, CONTROL \n\t MOV R1,#0X02 \n\t ORR R0, R0,R1 \n\t MSR CONTROL, R0")
#define OS_SWITCH_SP_TO_MSP					__asm volatile("MRS R0, CONTROL \n\t MOV R1,#0X05 \n\t AND R0, R0,R1 \n\t MSR CONTROL, R0")

#define OS_Generate_Exeption				__asm volatile("SVC #0X03")


enum CPUaccesslevel{
	privileged,
	unprivileged
};


void SVC_Handler ()
{
	SWITCH_CPU_AccessLevel(privileged);
}

void SWITCH_CPU_AccessLevel(enum CPUaccesslevel level)
{
	switch (level) {
		case privileged:
			__asm("MRS R0 ,CONTROL \n\t"
				  "LSR R0, #1 \n\t"
				  "LSL R0, #1 \n\t"
				  "MSR CONTROL, R0");
			break;
		case unprivileged:
			__asm("MRS R0 ,CONTROL \n\t"
				  "ORR R0,#1\n\t"
					"MSR CONTROL, R0");
			break;
		default:
			break;
	}
}
void my_wait(int x)
{
	uint32_t i,j;
	for (i = 0; i < x; ++i)
		for (j = 0; j < 255; ++j);

}

void EXTI9_Callback (void)
{
	/*SWITCH_CPU_AccessLevel(privileged);
	LCD_clear_screen();
	IRQ_Flag =1;
	LCD_WRITE_STRING("IRQ EXTI9 is     happened _|- ");
	my_wait(1000);
	*/
	if (IRQ_Flag == 0)
	{
		Task_A_Flag =1;
		IRQ_Flag =1 ;
	}
	else if (IRQ_Flag == 1)
	{
		Task_B_Flag =1;
		IRQ_Flag =0 ;
	}
}

int Task_A ( int a, int b, int c)
{
	return a+b+c;
}


int Task_B( int a, int b, int c, int d)
{
	return a+b+c+d;
}

void Main_OS()
{
	//Main Stack
	_E_MSP= (_S_MSP - 512);

	// Task A
	_S_PSP_TA = (_E_MSP -8);
	_E_PSP_TA = (_S_PSP_TA - TaskA_Stack_Size);

	// Task B
	_S_PSP_TB = (_E_PSP_TA -8);
	_E_PSP_TB = (_S_PSP_TB - TaskB_Stack_Size);

	while(1){
		__asm("nop");
		if(Task_A_Flag == 1)
		{
			//set PSP Register = _S_PSP_TA
			OS_SET_PSP(_S_PSP_TA);
			//SP -> PSP
			OS_SWITCH_SP_TO_PSP;
			// Switch from privileged -> unprivileged
			SWITCH_CPU_AccessLevel(unprivileged);

			Task_A_Flag = Task_A(1, 2, 3);

			// Switch from unprivileged -> privileged
			OS_Generate_Exeption;
			//SP -> MSP
			OS_SWITCH_SP_TO_MSP;

		}
		else if (Task_B_Flag == 1)
		{
			//set PSP Register = _S_PSP_TB
			OS_SET_PSP(_S_PSP_TB);

			//SP -> PSP
			OS_SWITCH_SP_TO_PSP;
			// Switch from privileged -> unprivileged
			SWITCH_CPU_AccessLevel(unprivileged);

			Task_B_Flag = Task_B(1, 2, 3, 4);

			// Switch from unprivileged -> privileged
			OS_Generate_Exeption;

			//SP -> MSP
			OS_SWITCH_SP_TO_MSP;
		}
	}

}


int main(void)
{
	/* Enable Clock */
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();

	EXTI_GPIO_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTIPB9;
	EXTI_CFG.Trigger_Case =EXTI_Trigger_Rising;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_Callback;
	EXTI_CFG.IRQ_EN =EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
	//IRQ_Flag=1;

	Main_OS();

	while (1)
	{
		if(IRQ_Flag)
		{
			LCD_clear_screen();
			IRQ_Flag =0;

		}
	}
}
