/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103x6.h"
#include "Stm32_F103C6_EXTI_drivers.h"
#include "Stm32_F103C6_gpio_drivers.h"
#include "Stm32_F103C6_USART_drivers.h"

#include "KEY_PAD.h"
#include "LCD.h"

void clock_init() {
	//Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
	//Enable clock GPIOB
	RCC_AFIO_CLK_EN();
}

uint16_t ch;
int main(void)
{
	UART_Config uartCfg;

	clock_init();
	uartCfg.BaudRate = UART_BaudRate_115200;
	uartCfg.HwFlowCtl = UART_HwFlowCtl_NONE;
	uartCfg.IRQ_Enable = UART_IRQ_Enable_NONE;
	uartCfg.P_IRQ_CallBack = NULL;
	uartCfg.Parity = UART_Parity_NONE;
	uartCfg.Payload_length = UART_Payload_length_8B;
	uartCfg.StopBits = UART_StopBits_1;
	uartCfg.Mode = UART_Mode_TX_RX;
	MCAL_UART_Init(USART1, &uartCfg);
	MCAL_UART_GPIO_Set_Pins(USART1);



	while(1)
	{
		MCAL_UART_ReceiveData(USART1, &ch, enable);
		MCAL_UART_SendData(USART1, &ch, enable);
	}
}
