/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "KEY_PAD.h"
#include "LCD.h"
#include "Stm32_F103C6_gpio_drivers.h"
#include "stm32f103x6.h"

// 7-segment values
#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10


void clock_init() {
	//Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB Bit 3 IOPBEN: IO port B clock enable
	RCC_GPIOB_CLK_EN();
}

void wait_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++);
}

// init GPIO pins fo 7-segment

void GPIOB_init()
{
	PINCONFIG.GPIO_PinNumber = GPIO_PIN_9;
	PINCONFIG.GPIO_MODE = GPIO_MODE_OUTPT_PP;
	PINCONFIG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PINCONFIG);

	PINCONFIG.GPIO_PinNumber = GPIO_PIN_10;
	PINCONFIG.GPIO_MODE = GPIO_MODE_OUTPT_PP;
	PINCONFIG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PINCONFIG);

	PINCONFIG.GPIO_PinNumber = GPIO_PIN_11;
	PINCONFIG.GPIO_MODE = GPIO_MODE_OUTPT_PP;
	PINCONFIG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PINCONFIG);

	PINCONFIG.GPIO_PinNumber = GPIO_PIN_12;
	PINCONFIG.GPIO_MODE = GPIO_MODE_OUTPT_PP;
	PINCONFIG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PINCONFIG);

	PINCONFIG.GPIO_PinNumber = GPIO_PIN_13;
	PINCONFIG.GPIO_MODE = GPIO_MODE_OUTPT_PP;
	PINCONFIG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PINCONFIG);

	PINCONFIG.GPIO_PinNumber = GPIO_PIN_14;
	PINCONFIG.GPIO_MODE = GPIO_MODE_OUTPT_PP;
	PINCONFIG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PINCONFIG);

	PINCONFIG.GPIO_PinNumber = GPIO_PIN_15;
	PINCONFIG.GPIO_MODE = GPIO_MODE_OUTPT_PP;
	PINCONFIG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PINCONFIG);

}

int main(void)
{
	clock_init();
	LCD_INIT();
	GPIOB_init();

	uint8_t key_value;

	LCD_WRITE_STRING("  Omar Ashraf");
	LCD_WRITE_COMMAND(LCD_BEGIN_AT_SECOND_ROW);
	LCD_WRITE_STRING(" learn In Depth");
	wait_ms(500);
	LCD_clear_screen();

	uint8_t LCD_DISPLAY[11] = {'0','1','2','3','4','5','6','7','8','9','0'};
	uint8_t DISPLAY[11] = {ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO};

	for (uint8_t i = 0; i < 11; ++i) {
		LCD_WRITE_CHAR(LCD_DISPLAY[i]);
		MCAL_GPIO_WritePort(GPIOB,DISPLAY[i] << 9 );
		wait_ms(100);
	}


	LCD_clear_screen();
	Keypad_init();
	LCD_WRITE_STRING("Keypad is ready");
	wait_ms(30);
	LCD_clear_screen();

	while (1)
	{
		key_value = Keypad_getkey();
		switch (key_value) {
			case 'E':
				break;
			case '?':
				LCD_clear_screen();
				break;
			default:
				LCD_WRITE_CHAR(key_value);
				break;
		}
	}
}
